### PR TITLE
Cookie updated by NetworkToCode Cookie Drift Manager Tool

### PR DESCRIPTION
**Pull request by snaselj**
# Closes NaN

## To Do

- [ ] Change the template ref to be stable

## From Drift Manager

Template:

```
{
    "template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
    "dir": "nautobot-app",
    "ref": "develop",
    "path": null
}
```

Cookie:

```
{
    "remote": "https://github.com/nautobot/nautobot-plugin-secrets-providers.git",
    "path": "/opt/ntc/outputs/nautobot-plugin-secrets-providers",
    "repository_path": "/opt/ntc/outputs/nautobot-plugin-secrets-providers",
    "dir": "",
    "branch_prefix": "drift-manager",
    "context": {
        "codeowner_github_usernames": "@smith-ntc",
        "full_name": "Network to Code, LLC",
        "email": "info@networktocode.com",
        "github_org": "nautobot",
        "plugin_name": "nautobot_secrets_providers",
        "verbose_name": "Nautobot's Secrets Providers Plugin",
        "plugin_slug": "nautobot-secrets-providers",
        "project_slug": "nautobot-plugin-secrets-providers",
        "repo_url": "https://github.com/nautobot/nautobot-plugin-secrets-providers",
        "base_url": "secrets-providers",
        "min_nautobot_version": "1.4.0",
        "max_nautobot_version": "1.9999",
        "nautobot_version": "latest",
        "camel_name": "NautobotSecretsProviders",
        "project_short_description": "Nautobot's Secrets Providers Plugin",
        "version": "0.1.0",
        "model_class_name": "None",
        "open_source_license": "Apache-2.0",
        "docs_base_url": "https://docs.nautobot.com",
        "docs_app_url": "https://docs.nautobot.com/projects/secrets-providers/en/latest",
        "_template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
        "_output_dir": "/opt/ntc/outputs",
        "_repo_dir": "/home/jsn/.cookiecutters/cookiecutter-nautobot-app/nautobot-app"
    },
    "base_branch": "develop",
    "remote_name": "origin"
}
```

CLI Arguments:

```
{
    "cookie_dir": "",
    "input": false,
    "json_filename": "",
    "output_dir": "/opt/ntc/outputs",
    "push": true,
    "template": "https://github.com/nautobot/cookiecutter-nautobot-app.git",
    "template_dir": "nautobot-app",
    "template_ref": "develop"
}
```

### CODE REVIEW

**Comment by snaselj** [comment]
Merged with `next-2.0` to resolve conflicts.

**Comment by snaselj** [comment]
Ready for review

**Review by bryanculver — APPROVED** [review]
Let's make sure CI passes, otherwise this is good.

**Comment by snaselj** [comment]
`nb-incorrect-base-class` pylint issues are resolved in #105, will rebase it after merging this one.

The other pylint issue with `requests_mock` is fixed.

**Comment by bryanculver** [comment]
@snaselj please address the merge conflicts

**Pull request merged**
